sudo: required
services:
  - docker

before_install:
  - docker build -t phunhakent/mutli-cont-client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run phunhakent/mutli-cont-client-test npm run test -- --coverage

after_success:
  # build product version of all services
  - docker build -t phunhakent/mutli-cont-client -f ./client/Dockerfile.prod ./client
  - docker build -t phunhakent/mutli-cont-nginx -f ./nginx/Dockerfile.prod ./nginx
  - docker build -t phunhakent/mutli-cont-server -f ./server/Dockerfile.prod ./server
  - docker build -t phunhakent/mutli-cont-worker -f ./worker/Dockerfile.prod ./worker

  # log in to the docker CLI
  - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD"

  # take all images and push them to Docker Hub
  - docker push phunhakent/mutli-cont-client
  - docker push phunhakent/mutli-cont-nginx
  - docker push phunhakent/mutli-cont-server
  - docker push phunhakent/mutli-cont-worker
