sudo: required
servers:
  - docker

before_install:
  - docker build -t phunhakent/mutli-cont-client-test -f ./client/Dockerfile.dev .

scripts:
  - docker run punhakent/mutli-cont-client-test npm run test -- --coverage

after_success:
  # build product version of all services
  - docker build -t punhakent/mutli-cont-client -f ./client/Dockerfile.prod .
  - docker build -t punhakent/mutli-cont-nginx -f ./nginx/Dockerfile.prod .
  - docker build -t punhakent/mutli-cont-server -f ./server/Dockerfile.prod .
  - docker build -t punhakent/mutli-cont-worker -f ./worker/Dockerfile.prod .

  # log in to the docker CLI
  - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD"

  # take all images and push them to Docker Hub
  - docker push punhakent/mutli-cont-client
  - docker push punhakent/mutli-cont-nginx
  - docker push punhakent/mutli-cont-server
  - docker push punhakent/mutli-cont-worker

